// Azure Functions (Consumption plan) — hosts the /api/getPins and auth stub endpoints.
// Storage account is required by the Functions runtime.

param name string
param location string
param tags object = {}
param keyVaultUri string
param allowedOrigin string = 'https://munchhatmap.dotheneedful.dev'

// Azure resource endpoints — not secrets, passed as plain env vars
param cosmosEndpoint string
param openAiEndpoint string = ''
param openAiDeployment string = 'gpt-4.1'

// Discord OAuth2 plain env vars
param discordClientId string
param discordGuildId string
param discordRedirectUri string
param discordModRoleId string = ''

// Pre-created managed identity (from identities module)
param functionIdentityId string
param functionClientId string

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: '${replace(name, '-', '')}sa'
  location: location
  tags: tags
  sku: {
    name: 'Standard_LRS' // Cheapest redundancy option
  }
  kind: 'StorageV2'
  properties: {
    accessTier: 'Hot'
    allowBlobPublicAccess: false // private — images served via SAS URLs generated by the API
    minimumTlsVersion: 'TLS1_2'
    // Note: network access restriction (networkAcls) is NOT applied here because this storage
    // account also serves as the Functions runtime (AzureWebJobsStorage). Consumption plan does
    // not support storage firewall without VNet integration. Security is provided by:
    //   - allowBlobPublicAccess: false (no public containers)
    //   - pin-images container private, served only via short-lived SAS URLs
    //   - Managed identity RBAC for bot uploads and API SAS generation
  }
}

// Private container for bot-uploaded pin images.
// Access is controlled via User Delegation SAS tokens generated by the API managed identity.
resource pinImagesContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2023-05-01' = {
  name: '${storageAccount.name}/default/pin-images'
  properties: {
    publicAccess: 'None'
  }
}

resource hostingPlan 'Microsoft.Web/serverfarms@2023-12-01' = {
  name: '${name}-plan'
  location: location
  tags: tags
  sku: {
    name: 'Y1'
    tier: 'Dynamic'
  }
  kind: 'functionapp'
  properties: {}
}

resource functionApp 'Microsoft.Web/sites@2023-12-01' = {
  name: name
  location: location
  tags: tags
  kind: 'functionapp'
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${functionIdentityId}': {}
    }
  }
  properties: {
    serverFarmId: hostingPlan.id
    httpsOnly: true
    // Tell the Functions runtime to use the user-assigned identity when resolving
    // @Microsoft.KeyVault() references in app settings (default would be SystemAssigned
    // which doesn't exist here and causes KV references to silently return the literal string)
    keyVaultReferenceIdentity: functionIdentityId
    siteConfig: {
      nodeVersion: '~20'
      appSettings: [
        {
          name: 'AzureWebJobsStorage'
          value: 'DefaultEndpointsProtocol=https;AccountName=${storageAccount.name};AccountKey=${storageAccount.listKeys().keys[0].value};EndpointSuffix=${environment().suffixes.storage}'
        }
        {
          name: 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING'
          value: 'DefaultEndpointsProtocol=https;AccountName=${storageAccount.name};AccountKey=${storageAccount.listKeys().keys[0].value};EndpointSuffix=${environment().suffixes.storage}'
        }
        {
          name: 'WEBSITE_CONTENTSHARE'
          value: toLower(name)
        }
        {
          name: 'FUNCTIONS_EXTENSION_VERSION'
          value: '~4'
        }
        {
          name: 'FUNCTIONS_WORKER_RUNTIME'
          value: 'node'
        }
        {
          name: 'WEBSITE_NODE_DEFAULT_VERSION'
          value: '~20'
        }
        // Cosmos DB — managed identity auth (no key needed)
        {
          name: 'COSMOS_DB_ENDPOINT'
          value: cosmosEndpoint
        }
        {
          name: 'ALLOWED_ORIGIN'
          value: allowedOrigin
        }
        // Blob storage — managed identity auth; only account name needed (no key)
        {
          name: 'AZURE_STORAGE_ACCOUNT_NAME'
          value: storageAccount.name
        }
        {
          name: 'IMAGE_STORAGE_CONTAINER'
          value: 'pin-images'
        }
        // Required for DefaultAzureCredential to select the correct user-assigned identity
        {
          name: 'AZURE_CLIENT_ID'
          value: functionClientId
        }
        // Discord OAuth2 — plain env vars (not secrets)
        {
          name: 'DISCORD_CLIENT_ID'
          value: discordClientId
        }
        {
          name: 'DISCORD_GUILD_ID'
          value: discordGuildId
        }
        {
          name: 'DISCORD_REDIRECT_URI'
          value: discordRedirectUri
        }
        {
          name: 'DISCORD_MOD_ROLE_ID'
          value: discordModRoleId
        }
        // Azure OpenAI — for reverse geocoding on pin location updates
        {
          name: 'AZURE_OPENAI_ENDPOINT'
          value: openAiEndpoint
        }
        {
          name: 'AZURE_OPENAI_DEPLOYMENT'
          value: openAiDeployment
        }
        // Discord OAuth2 client secret and JWT session secret — from Key Vault
        {
          name: 'DISCORD_CLIENT_SECRET'
          value: '@Microsoft.KeyVault(SecretUri=${keyVaultUri}secrets/discord-oauth-client-secret/)'
        }
        {
          name: 'SESSION_SECRET'
          value: '@Microsoft.KeyVault(SecretUri=${keyVaultUri}secrets/session-secret/)'
        }
      ]
      cors: {
        allowedOrigins: [
          allowedOrigin
        ]
        supportCredentials: true // required for cross-origin cookie auth (SameSite=None)
      }
    }
  }
}

output functionAppName string = functionApp.name
output functionAppHostname string = functionApp.properties.defaultHostName
output storageAccountName string = storageAccount.name
output storageAccountId string = storageAccount.id
